PWA-152, PWA-345 Add frontend subscription for register process
shopgate/ext-bigcommerce-user pull request #4
Opened 2018-05-09 13:45 UTC by alexbridge

2018-05-09 13:56 UTC, SG-Noxoreos approved these changes

2018-05-14 06:20 UTC, Menes1337 commented on frontend/.npmrc
> +package-lock=false
we shouldn't prevent npm from creating a package-lock.json. Most security tools won't be able to check for security issues. (like npm audit (https://docs.npmjs.com/getting-started/running-a-security-audit) or the former nsp [https://github.com/nodesecurity/nsp]).
But we still can put the package-lock.json to the .gitignore and don't commit the file to our repository

2018-05-14 06:21 UTC, Menes1337 requested changes
please remove .npmrc

2018-05-15 05:44 UTC, Menes1337 approved these changes

2018-05-15 07:15 UTC, merged